name: External Trigger Release

on:
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:

jobs:
  external-trigger-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: External Trigger
        run: |
          if [ -n "${{ secrets.PAUSE_EXTERNAL_TRIGGER_LSKY_PRO_X_MASTER }}" ]; then
            echo "**** Github secret PAUSE_EXTERNAL_TRIGGER_LSKY_PRO_X_MASTER is set; skipping trigger. ****"
            exit 0
          fi
          echo "**** External trigger running off of master branch. To disable this trigger, set a Github secret named \"PAUSE_EXTERNAL_TRIGGER_LSKY_PRO_X_MASTER\". ****"
          
          echo "**** Retrieving external version ****"
          EXT_RELEASE=$(curl -sX GET "https://api.github.com/repos/lsky-org/lsky-pro/releases/latest" | jq -r '.tag_name')
          if [ -z "${EXT_RELEASE}" ] || [ "${EXT_RELEASE}" == "null" ]; then
            echo "**** Can't retrieve external version, exiting ****"
            FAILURE_REASON="Can't retrieve external version for lsky-pro branch master"
            GHA_TRIGGER_URL="https://github.com/tyroyal/lsky-pro-x/actions/runs/${{ github.run_id }}"
            MESSAGE='<font color=\"info\">Lsky-pro-x</font> **Trigger Failed**\n**Reason:** <font color=\"warning\">'"${FAILURE_REASON}"'</font> \n**Trigger URL:** ['"${GHA_TRIGGER_URL}"']('"${GHA_TRIGGER_URL}"')'
            curl ${{ secrets.WECHAT_WEBHOOK }} -sX POST -H "Content-Type: application/json" --data '{"msgtype": "markdown", "markdown": {"content": "'"${MESSAGE}"'"}}' 
            exit 1
          fi
          EXT_RELEASE=$(echo ${EXT_RELEASE} | sed 's/[~,%@+;:/]//g')
          echo "**** External version: ${EXT_RELEASE} ****"

          echo "**** Retrieving last pushed version ****"
          image="tyroyal/lsky-pro-x"
          tag="latest"
          token=$(curl -sX GET \
            "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${image}:pull" \
            | jq -r '.token')
          multidigest=$(curl -sX GET \
            --header "Accept: application/vnd.docker.distribution.manifest.list.v2+json" \
            --header "Authorization: Bearer ${token}" \
            "https://index.docker.io/v2/${image}/manifests/${tag}" \
            | jq -r 'first(.manifests[].digest)')
          digest=$(curl -sX GET \
            --header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            --header "Authorization: Bearer ${token}" \
            "https://index.docker.io/v2/${image}/manifests/${multidigest}" \
            | jq -r '.config.digest')
          image_info=$(curl -sLX GET \
            --header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            --header "Authorization: Bearer ${token}" \
            "https://index.docker.io/v2/${image}/blobs/${digest}" \
            | jq -r '.config')
          IMAGE_VERSION=$(echo ${image_info} | jq -r '.Labels.build_version' | awk '{print $3}')
          if [ -z "${IMAGE_VERSION}" ]; then
            echo "**** Can't retrieve last pushed version, exiting ****"
            FAILURE_REASON="Can't retrieve last pushed version for lsky-pro tag latest"
            MESSAGE='**Trigger Failed** \n**Reason:** '"${FAILURE_REASON}"' \n'
            curl ${{ secrets.WECHAT_WEBHOOK }} -sX POST -H "Content-Type: application/json" --data '{"msgtype": "markdown", "markdown": {"content": "'"${MESSAGE}"'"}}'
            exit 1
          fi
          echo "**** Last pushed version: ${IMAGE_VERSION} ****"

          if [ "${EXT_RELEASE}" == "${IMAGE_VERSION}" ]; then
            echo "**** Version ${EXT_RELEASE} already pushed, exiting ****"
            exit 0
          else
            echo "**** New version ${EXT_RELEASE} found; old version was ${IMAGE_VERSION}. Triggering new build ****"
            WORKFLOW_ID=$(curl -sX GET "https://api.github.com/repos/tyroyal/lsky-pro-x/actions/workflows" | jq -r '.workflows[]|(select(.name=="docker-release")).id')
            curl -isX POST \
                  -H "Authorization: token ${{ secrets.CR_PAT }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -d '{"ref":"refs/heads/master","inputs":{"tag":"'"${EXT_RELEASE}"'"}}' \
                  https://api.github.com/repos/tyroyal/lsky-pro-x/actions/workflows/docker-release.yml/dispatches
            sleep 10
            buildurl=$(curl -sX GET https://api.github.com/repos/tyroyal/lsky-pro-x/actions/workflows/${WORKFLOW_ID}/runs | jq -r '.workflow_runs[0].html_url')
            echo "**** Github action run job build url: ${response} ****"

            echo "**** Notifying WeChat ****"
            TRIGGER_REASON="A version change was detected for lsky-pro tag latest. Old version:${IMAGE_VERSION} New version:${EXT_RELEASE}"
            MESSAGE='**Build Triggered** \n**Reason:** '"${TRIGGER_REASON}"' \n**Build URL:** '"${buildurl}"' \n'
            curl ${{ secrets.WECHAT_WEBHOOK }} -sX POST -H "Content-Type: application/json" --data '{"msgtype": "markdown", "markdown": {"content": "'"${MESSAGE}"'"}}'
          fi
